dist: xenial
language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=26
 - ANDROID_BUILD_TOOLS=29.0.1
  #  - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - build-tools-29.0.1
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra-android-support
  - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - '.+'
script:
  - ./gradlew assembleRelease

before_install:
  - yes | sdkmanager "platforms;android-26"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
