language: android

env:
 global:
 - ANDROID_API=26
 - ANDROID_BUILD_TOOLS=29.0.1

android:
  components:
  - tools
  - build-tools-29.0.1
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra-android-support
  - extra-android-m2repository
script:
  - ./gradlew :app:assembleRelease

before_install:
sdkmanager "platform-tools" "build-tools;29.0.1" "platforms;android-26"