language: android  
android:
  components:
    - tools
    - build-tools-29.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:  
  - ./gradlew assembleRelease